=== inf2425tig04/trabalho_ti/cursos_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="cursos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="curso" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="nivel" type="xs:string"/>
              <xs:element name="instituicao" type="xs:string"/>
              <xs:element name="duracao" type="xs:string"/>
              <xs:element name="professores">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="professor" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nome" type="xs:string"/>
                          <xs:element name="especialidade" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== inf2425tig04/trabalho_ti/cursos.xml
<?xml version="1.0" encoding="UTF-8"?>
<cursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="cursos_schema.xsd">

  <curso id="c001">
    <nome>Licenciatura em Educação</nome>
    <nivel>Superior</nivel>
    <instituicao>Universidade de Lisboa</instituicao>
    <duracao>4 anos</duracao>
    <professores>
      <professor id="p01">
        <nome>Maria Silva</nome>
        <especialidade>Didática e Metodologia</especialidade>
      </professor>
      <professor id="p02">
        <nome>João Pereira</nome>
        <especialidade>Psicologia Educacional</especialidade>
      </professor>
    </professores>
  </curso>

  <curso id="c002">
    <nome>Curso Técnico em Informática</nome>
    <nivel>Profissional</nivel>
    <instituicao>Escola Secundária de Porto</instituicao>
    <duracao>3 anos</duracao>
    <professores>
      <professor id="p03">
        <nome>Ana Costa</nome>
        <especialidade>Programação</especialidade>
      </professor>
    </professores>
  </curso>

  <curso id="c003">
    <nome>Ensino Básico</nome>
    <nivel>Fundamental</nivel>
    <instituicao>Escola Básica nº 12</instituicao>
    <duracao>9 anos</duracao>
    <professores>
      <professor id="p04">
        <nome>Pedro Santos</nome>
        <especialidade>Matemática</especialidade>
      </professor>
      <professor id="p05">
        <nome>Carla Mendes</nome>
        <especialidade>Português</especialidade>
      </professor>
    </professores>
  </curso>

  <curso id="c004">
    <nome>Mestrado em Engenharia Civil</nome>
    <nivel>Pós-graduação</nivel>
    <instituicao>Universidade do Minho</instituicao>
    <duracao>2 anos</duracao>
    <professores>
      <professor id="p06">
        <nome>Luís Amaral</nome>
        <especialidade>Estruturas</especialidade>
      </professor>
      <professor id="p07">
        <nome>Teresa Sousa</nome>
        <especialidade>Materiais de Construção</especialidade>
      </professor>
    </professores>
  </curso>

  <curso id="c005">
    <nome>Licenciatura em Artes Visuais</nome>
    <nivel>Superior</nivel>
    <instituicao>Faculdade de Belas Artes</instituicao>
    <duracao>3 anos</duracao>
    <professores>
      <professor id="p08">
        <nome>Rita Borges</nome>
        <especialidade>Pintura</especialidade>
      </professor>
      <professor id="p09">
        <nome>Tiago Ferreira</nome>
        <especialidade>Escultura</especialidade>
      </professor>
    </professores>
  </curso>

  <curso id="c006">
    <nome>Ensino Secundário - Ciências e Tecnologias</nome>
    <nivel>Secundário</nivel>
    <instituicao>Escola Secundária D. Dinis</instituicao>
    <duracao>3 anos</duracao>
    <professores>
      <professor id="p10">
        <nome>Sónia Almeida</nome>
        <especialidade>Física e Química</especialidade>
      </professor>
      <professor id="p11">
        <nome>Bruno Neves</nome>
        <especialidade>Biologia e Geologia</especialidade>
      </professor>
    </professores>
  </curso>

</cursos>
