=== inf2425tig04/trabalho_ti/src/cursos_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="cursos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="curso" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="nivel" type="xs:string"/>
              <xs:element name="instituicao" type="xs:string"/>
              <xs:element name="duracao" type="xs:string"/>
              <xs:element name="inscritos_1ano_2022" type="xs:int"/>
              <xs:element name="taxa_abandono_1ano" type="xs:decimal"/>
              <!-- Taxas de conclusÃ£o, opcionais -->
              <xs:element name="taxa_conclusao_4anos" type="xs:decimal" minOccurs="0"/>
              <xs:element name="taxa_conclusao_5anos" type="xs:decimal" minOccurs="0"/>
              <xs:element name="taxa_conclusao_6anos" type="xs:decimal" minOccurs="0"/>
              <xs:element name="taxa_empregabilidade_ano1" type="xs:decimal"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== inf2425tig04/trabalho_ti/src/cursos.xml
<?xml version="1.0" encoding="UTF-8"?>
<cursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="cursos_schema.xsd">

  <curso id="c001">
    <nome>Licenciatura em Educação</nome>
    <nivel>Superior</nivel>
    <instituicao>Universidade de Lisboa</instituicao>
    <duracao>4 anos</duracao>
    <inscritos_1ano_2022>4800</inscritos_1ano_2022>
    <taxa_abandono_1ano>0.10</taxa_abandono_1ano>
    <taxa_conclusao_6anos>0.82</taxa_conclusao_6anos>
    <taxa_empregabilidade_ano1>0.79</taxa_empregabilidade_ano1>
  </curso>

  <curso id="c002">
    <nome>Licenciatura em Engenharia Informática</nome>
    <nivel>Superior</nivel>
    <instituicao>Universidade do Porto</instituicao>
    <duracao>3 anos</duracao>
    <inscritos_1ano_2022>2600</inscritos_1ano_2022>
    <taxa_abandono_1ano>0.11</taxa_abandono_1ano>
    <taxa_conclusao_5anos>0.85</taxa_conclusao_5anos>
    <taxa_empregabilidade_ano1>0.91</taxa_empregabilidade_ano1>
  </curso>

  <curso id="c003">
    <nome>Licenciatura em Artes Visuais</nome>
    <nivel>Superior</nivel>
    <instituicao>Faculdade de Belas Artes</instituicao>
    <duracao>3 anos</duracao>
    <inscritos_1ano_2022>600</inscritos_1ano_2022>
    <taxa_abandono_1ano>0.15</taxa_abandono_1ano>
    <taxa_conclusao_5anos>0.75</taxa_conclusao_5anos>
    <taxa_empregabilidade_ano1>0.65</taxa_empregabilidade_ano1>
  </curso>

  <curso id="c004">
    <nome>Licenciatura em Engenharia Informática</nome>
    <nivel>Superior</nivel>
    <instituicao>Universidade Nova de Lisboa</instituicao>
    <duracao>3 anos</duracao>
    <inscritos_1ano_2022>2300</inscritos_1ano_2022>
    <taxa_abandono_1ano>0.13</taxa_abandono_1ano>
    <taxa_conclusao_5anos>0.83</taxa_conclusao_5anos>
    <taxa_empregabilidade_ano1>0.89</taxa_empregabilidade_ano1>
  </curso>

  <curso id="c005">
    <nome>Licenciatura em Gestão</nome>
    <nivel>Superior</nivel>
    <instituicao>Universidade do Minho</instituicao>
    <duracao>3 anos</duracao>
    <inscritos_1ano_2022>3100</inscritos_1ano_2022>
    <taxa_abandono_1ano>0.09</taxa_abandono_1ano>
    <taxa_conclusao_5anos>0.78</taxa_conclusao_5anos>
    <taxa_empregabilidade_ano1>0.86</taxa_empregabilidade_ano1>
  </curso>

  <curso id="c006">
    <nome>Licenciatura em Psicologia</nome>
    <nivel>Superior</nivel>
    <instituicao>Universidade de Coimbra</instituicao>
    <duracao>3 anos</duracao>
    <inscritos_1ano_2022>2100</inscritos_1ano_2022>
    <taxa_abandono_1ano>0.14</taxa_abandono_1ano>
    <taxa_conclusao_5anos>0.77</taxa_conclusao_5anos>
    <taxa_empregabilidade_ano1>0.72</taxa_empregabilidade_ano1>
  </curso>

  <curso id="c007">
    <nome>Licenciatura em Economia</nome>
    <nivel>Superior</nivel>
    <instituicao>Universidade de Lisboa</instituicao>
    <duracao>3 anos</duracao>
    <inscritos_1ano_2022>2700</inscritos_1ano_2022>
    <taxa_abandono_1ano>0.08</taxa_abandono_1ano>
    <taxa_conclusao_5anos>0.80</taxa_conclusao_5anos>
    <taxa_empregabilidade_ano1>0.85</taxa_empregabilidade_ano1>
  </curso>

  <curso id="c008">
    <nome>Licenciatura em Biologia</nome>
    <nivel>Superior</nivel>
    <instituicao>Universidade do Porto</instituicao>
    <duracao>3 anos</duracao>
    <inscritos_1ano_2022>1900</inscritos_1ano_2022>
    <taxa_abandono_1ano>0.12</taxa_abandono_1ano>
    <taxa_conclusao_5anos>0.74</taxa_conclusao_5anos>
    <taxa_empregabilidade_ano1>0.69</taxa_empregabilidade_ano1>
  </curso>

</cursos>
